import axios from 'axios';
import { useSession } from 'next-auth/react';
import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import { useTheme } from '../../context/UserProvider';

export default function Home() {
  const { user, setUser } = useTheme();
  const [users, setUsers] = useState<User | null>(null);
  const [dataa, setData] = useState<ResponseData | null>(null);
  const { data: session, status } = useSession();

  useEffect(() => {
    if (session && session.user) {
      const { name, email } = session.user;
      if (!name || !email) {
        return;
      } else {
        const handlePost = async () => {
          const data = {
            name: name,
            email: email,
          };
          if (dataa == null) {
            const response = await axios.post<ResponseData>(
              '/api/user/post',
              data
            );
            // console.log(response.data);
            setData(response.data);
            setUsers(response.data.data);

            setUser?.(response.data.data);
          }
        };
        handlePost();
      }

      console.log(user);

      // fetchUser(email);
    }
  }, [session, dataa, users]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <p>this is body.</p>
      </div>
    </>
  );
}
