import type { NextPage } from 'next';
import Head from 'next/head';
import { io, Socket } from 'socket.io-client';

import IndexNotification from '../../components/notification/bunch/IndexNotification';
import styles from '../styles/index.module.css';
import { useEffect, useState, useContext } from 'react';
import React from 'react';
import { SocketContext } from '../../context/SpcketProvider';

// const END_POINTS = 'https://6669-103-115-183-168.in.ngrok.io';

type Notification = {
  _id: string;
  user: string;
  post: string;
};

const Notification: NextPage = () => {
  const [notifications, setNotifications] = useState<any>([]);
  const { socket } = useContext(SocketContext);

  // useEffect(() => {
  //   socket?.on('getNotification', (data) => {
  //     console.log(data);
  //     setNotifications((prev: any) => [...prev, data]);
  //   });
  // }, [socket]);

  return (
    <div>
      <Head>
        <title>Notification</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className={styles.index__container}>
        <div className={styles.index__content}>
          <IndexNotification />
        </div>
        <ul>
          {/* {notifications.map((notification) => (
            <li key={notification._id}>
              User {notification.user} created a new tweet {notification.post}
            </li>
          ))} */}
        </ul>
      </div>
    </div>
  );
};

export default Notification;
