import Head from 'next/head';
import { useTheme } from '../../context/UserProvider';
('../../components/feeds/bunch/IndexPageFeed');
import styles from '../../styles/index.module.css';
import Profile from '../../components/profile/bunch/ProfileIndex';

export default function Home() {
  const { user } = useTheme();
  console.log(user);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Profile />
    </>
  );
}
